SKILL_ALIASES = {
    "Python": ["python", "py"],
    "SQL": ["sql", "mysql", "sqlite", "ms sql", "mssql", "sql server", "postgresql", "postgres"],
    "React": ["react", "react.js", "reactjs", "react js"],
    "Node.js": ["node.js", "nodejs", "node js", "node", "express", "express.js"],
    "JavaScript": ["javascript", "java script", "js", "ecmascript"],
    "TypeScript": ["typescript", "type script", "ts"],
    "MongoDB": ["mongodb", "mongo db", "mongoose"],
    "PostgreSQL": ["postgresql", "postgres", "pg"],
    "AWS": ["aws", "amazon web services", "ec2", "s3", "lambda"],
    "Docker": ["docker", "containerization", "containers"],
    "FastAPI": ["fastapi", "fast api"],
    "Machine Learning": ["machine learning", "machine-learning", "ml", "scikit-learn", "sklearn"],
    "Deep Learning": ["deep learning", "deep-learning", "dl"],
    "PyTorch": ["pytorch", "torch"],
    "TensorFlow": ["tensorflow", "tf", "keras"],
    "LLM": ["llm", "llms", "large language model", "large language models"],
    "NLP": ["nlp", "natural language processing"],
    "RAG": ["rag", "retrieval augmented generation", "retrieval-augmented generation"],
    "LangChain": ["langchain", "lang chain"],
    "OpenAI": ["openai", "gpt", "chatgpt"],
    "Gemini": ["gemini", "google gemini"],
    "Hugging Face": ["hugging face", "huggingface", "transformers"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy", "num py"],
    "Scikit-learn": ["scikit-learn", "sklearn"],
    "Java": ["java"],
    "C++": ["c++", "cpp"],
    "C": [" c ", " c\n", " c,"],
    "HTML": ["html", "html5", "html/css"],
    "CSS": ["css", "css3", "tailwind", "html/css"],
    "Git": ["git", "github", "gitlab"],
    "REST API": [
        "rest api",
        "rest apis",
        "restful api",
        "restful apis",
        "rest api development",
        "restful",
        "api development",
        "rest",
    ],
    "GraphQL": ["graphql", "graph ql"],
    "Flask": ["flask"],
    "Django": ["django"],
    "Linux": ["linux", "ubuntu"],
    "Kubernetes": ["kubernetes", "k8s", "kubernates"],
    "Azure": ["azure", "microsoft azure"],
    "GCP": ["gcp", "google cloud"],
    "Power BI": ["power bi", "powerbi", "power-bi"],
    "Tableau": ["tableau"],
    "Spring Boot": ["spring boot", "springboot"],
    "Algorithms": ["algorithms", "algoritms", "data structures and algorithms"],
    "Data Structures": ["data structure", "data structures", "data-structure"],
    "Competitive Programming": ["competitive programming"],
    "Data Visualization": ["data visualization", "data-viz", "matplotlib", "seaborn"],
    "CI/CD": ["ci/cd", "cicd", "continuous integration", "continuous deployment"],
    "Vue": ["vue", "vue.js", "vuejs"],
    "UI/UX": ["ui/ux", "ui ux", "user experience", "user interface"],
}

SKILLS = list(SKILL_ALIASES.keys())

CANONICAL_SKILL_LOOKUP = {}
for canonical, aliases in SKILL_ALIASES.items():
    CANONICAL_SKILL_LOOKUP[canonical.lower()] = canonical
    for alias in aliases:
        CANONICAL_SKILL_LOOKUP[alias.lower()] = canonical
